hackathon/hackathon/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^member/',include('member.urls',namespace='member')),
    url(r'^poll/',include('poll.urls',namespace='poll')),
]

hackathon/member/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.login, name='login'),
    url(r'^fb_login/$',views.fb_login,name='fb_login'),
    url(r'^logout/$',views.logout,name='logout'),
]

hackathon/poll/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^poll_list/$',views.poll_list,name='poll_list'),
    url(r'^poll_edit/$',views.poll_edit,name='poll_edit'),
    url(r'^poll_detail/(?P<poll_id>\d+)/$',views.poll_detail,name='poll_detail'),
    url(r'^poll_result/(?P<poll_id>\d+)/$',views.poll_result,name='poll_result'),
    url(r'^like/(?P<com_id>\d+)/$', views.like, name='like'),

]

hackathon/member/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin


class ServiceUserManager(BaseUserManager):
    def create_user(self,
                    user_info):

        user = self.model(email=user_info['email'],
                          last_name=user_info['last_name'],
                          first_name=user_info['first_name'],
                          facebook_id=user_info['id'])
        if user.email=='arcanelux@gmail.com':
            user.is_teacher=True
        user.save()
        return user

    def create_superuser(self,
                         email,
                         last_name,
                         first_name,
                         password):
        user = self.model(email=email,
                          last_name=last_name,
                          first_name=first_name
                          )
        user.set_password(password)
        user.is_staff=True
        user.is_superuser=True
        user.save()
        return user


class ServiceUser(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(unique=True)
    facebook_id = models.CharField(max_length=30)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    joined_date = models.DateTimeField(auto_now_add=True)
    is_teacher = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = ('email')
    REQUIRED_FIELDS = ('first_name','last_name')

    objects = ServiceUserManager()

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.first_name

hackathon/poll/models.py
from django.db import models
from member.models import ServiceUser


class Poll(models.Model):
    title = models.CharField(max_length=200)
    notification = models.CharField(max_length=200,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(ServiceUser)


class Result(models.Model):
    student = models.ForeignKey(ServiceUser)
    score = models.IntegerField(default=0)
    poll = models.ForeignKey(Poll)


class Comment(models.Model):
    student = models.ForeignKey(ServiceUser)
    poll = models.ForeignKey(Poll)
    text = models.CharField(max_length=200)


class Like(models.Model):
    student = models.ForeignKey(ServiceUser)
    comment = models.ForeignKey(Comment)
    like_val = models.IntegerField(default=0)

hackathon/poll/forms.py
from django import forms
from .models import Poll

class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ('title','notification')

hackathon/member/views.py
from django.shortcuts import render,reverse,redirect
from django.http import HttpResponse
from django.conf import settings
import requests
from .models import ServiceUser
from django.contrib.auth import authenticate as auth, login as auth_login, logout as auth_logout


def login(request):
    return render(request, 'member/login.html', {})


def fb_login(request):
    code = request.GET.get('code')


    redirect_uri = 'https://graph.facebook.com/v2'\
    '.8/oauth/access_token?'\
    'client_id={app_id}'\
    '&redirect_uri={redirect_url}'\
    '&client_secret={app_secret}'\
    '&code={code_parameter}'.format(app_id=settings.FACEBOOK_APP_ID,
                                   redirect_url='http://127.0.0.1:8000/member/fb_login/',
                                   app_secret=settings.APP_SECRET_CODE,
                                   code_parameter=code)
    r = requests.get(redirect_uri)
    dic_r = r.json()
    access_token = dic_r['access_token']
    app_secret_code = '{}|{}'.format(settings.FACEBOOK_APP_ID,settings.APP_SECRET_CODE)
    debug_redirect_uri = 'https://graph.facebook.com/debug_token?'\
                         'input_token={access_token}'\
                         '&access_token={app_secret_code}'.format(access_token=access_token,
                                                                 app_secret_code=app_secret_code)

    r = requests.get(debug_redirect_uri)
    dic_r = r.json()
    user_id = dic_r['data']['user_id']

    user_info_uri = 'https://graph.facebook.com/{user_id}?'\
                    'fields=id,email,first_name,last_name'\
                    '&access_token={access_token}'.format(user_id=user_id,
                                                          access_token=access_token)
    r = requests.get(user_info_uri)
    dic_r = r.json()
    user_info = dic_r

    try:
        user_id = ServiceUser.objects.get(email=dic_r['email'])
    except:
        user_id = ServiceUser.objects.create_user(dic_r)


    user = auth(user_info=user_info)
    auth_login(request,user)
    if user.is_teacher :
        return redirect('poll:poll_edit')
    else:
        return redirect('poll:poll_list')


def logout(request):
    auth_logout(request)
    return redirect('poll:poll_list')

hackathon/poll/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Poll, Result, Comment, Like
import json
from .forms import PollForm


def poll_list(request):
    polls = Poll.objects.all().order_by('-created_date')[:10]
    ret = {'polls':polls}

    return render(request,'poll/poll_list.html',ret)

def poll_edit(request):
    if request.method =='GET':
        form = PollForm()
        return render(request,'poll/poll_edit.html',{'form':form})
    elif request.method=='POST':
        form =PollForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            notification = form.cleaned_data['notification']
            author = request.user
            Poll.objects.create(title=title,
                                notification=notification,
                                author=author)
        else:
            return render(request, 'poll/poll_edit.html',{'form':form})
        return redirect('poll:poll_list')


def poll_detail(request,poll_id):
    poll = Poll.objects.get(pk=poll_id)
    if request.method=='POST':
        if request.POST['radio']:
            value = request.POST['radio']
            comment = request.POST['comment']
            print(value)
            Result.objects.create(
                student=request.user,
                poll=poll,
                score=value
            )
            Comment.objects.create(
                student=request.user,
                poll=poll,
                text=comment

            )
            return redirect('poll:poll_result',poll_id=poll_id)
        else:
            return redirect('poll:poll_detail',poll_id=poll.pk)
    elif request.method=="GET":
        context = {}
        context['poll']=poll
        return render(request,'poll/poll_detail.html',context)


def poll_result(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)

    ret = [
        Result.objects.filter(poll=poll,
                              score=i).count()
        for i in range(1, 6)
    ]

    tot = 0
    for ind, num in enumerate(ret):
        tot += (ind+1) * num

    student = Result.objects.filter(poll_id=poll_id).count()
    avg = tot/student

    comments = Comment.objects.filter(poll=poll)

    context = {'score': ret,
               'avg': avg,
               'comments': comments,
               'poll': poll}

    return render(request, 'poll/poll_result.html', context)


def like(request, com_id):
    like = Like.objects.get(comment=com_id)
    com = Comment.objects.get(comment=com_id)
    like.objects.add(sudent=request.user, comment=com)

hackathon/templates/common/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/poll.js' %}"></script>
    <title>Document</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <a href="" class="navbar-brand">강의평가</a>
      </div>

      <div class="collapse navbar-collapse" id="main-navbar">
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'poll:poll_list' %}">Poll</a>
          </li>
          <li>
            <a href="">Result</a>
          </li>
          <li>
            <a href="{% url 'poll:poll_edit' %}">Poll Add</a>
          </li>

          <li>
            <a href="{% url 'member:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'member:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% block login %}
{% endblock %}
{% if user.is_authenticated %}
{% block content %}
{% endblock %}
{% else %}
<h3>로그인 하세요</h3>
{% endif %}
</body>
</html>

hackathon/templates/member/login.html
{% extends 'common/base.html' %}

{% block login %}

    <a href="https://www.facebook.com/v2.8/dialog/oauth?
 client_id=923219767822683&response_type=code&scope=public_profile,email
 &redirect_uri=http://{{ request.META.HTTP_HOST }}{% url 'member:fb_login' %}">페이스북 로그인</a>

{% endblock %}

hackathon/templates/poll/poll_detail.html
{% extends 'common/base.html' %}

{% block content %}
    <div>
    <h2>{{ poll.title }}</h2>
    <p>{{ poll.notification }}</p>
    </div>
    <a href="{% url 'poll:poll_result' poll_id=poll.pk %}">Poll result</a>
    <form action="" method="POST">{% csrf_token %}
        <div>
        <input type="radio" name="radio" value="1">전혀 이해가 되지 않는다
        <input type="radio" name="radio" value="2">잘 모르겠다
        <input type="radio" name="radio" value="3">절반은 이해간다
        <input type="radio" name="radio" value="4">70%는 이해할 수 있다
        <input type="radio" name="radio" value="5">나는 다 알겠다
        </div>

        <input type="text" size="50" name="comment" placeholder="자유롭게 의견을 제시해주세요_퍼킹유세이 안됩니다">
        <button type="submit">의견 제출하기</button>
    </form>

{% endblock %}

hackathon/templates/poll/poll_edit.html
{% extends 'common/base.html' %}

{% block content %}
    <form action="" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">만들기</button>
    </form>
{% endblock %}

hackathon/templates/poll/poll_list.html
{% extends 'common/base.html' %}

{% block content %}

    {% for poll in polls %}
    <div>
    <h2><a href="{% url 'poll:poll_detail' poll_id=poll.pk %}">{{ poll.title }}</a></h2>
    <p>created_date: {{ poll.created_date }}</p>
    </div>
    {% endfor %}

{% endblock %}

hackathon/templates/poll/poll_result.html
{% extends 'common/base.html' %}

{% block content %}
    <div>
    <h2>{{ poll.title }}</h2>
    <div>
        <p>평균 : {{ avg|floatformat:1 }}</p>
        <p></p>
        <p>1점 하나도 이해 안가요 {{ score.0 }}명</p>
        <p>2점 많이 모르겠어요 {{ score.1 }}명</p>
        <p>3점 반은 알고 반은 모르겠어요 {{ score.2 }}명</p>
        <p>4점 70퍼센트는 이해되요 {{ score.3 }}명</p>
        <p>5점 저는 다 이해했어요 {{ score.4 }}명</p>
    </div>
</div>

<h4> 피드백 코멘트 </h4>

{% for comment in comments %}

    {% if comment.text %}

<div class="">{{ comment.text }}
    <button type="button" class="btn label label-info" data-toggle="tooltip"
    data-placement="right" id={{comment.id}} onclick="btnajax({{comment.id}})">
    <span class="glyphicon glyphicon-thumbs-up"></span>
    <span>{{comment.like_set.all | length}}</span>
</button>
</div>


{% endif %}
{% endfor %}
<script type="text/javascript">
    var csrftoken = Cookies.get("scrftoken");

    $.ajaxSetup({
        headers: {"X-CSRFToken": csrftoken}
    });
    function btnajax(id){
        alert($("#"+id).text())
        var url = "/poll/like/"+id+"/"
        $.ajax({
            url=url,
            type="post",
            data="",
            success: function(response){
                $("#"+id).text(response.cnt)
            }

        });
    }
</script>
{% endblock %}